### ISSUE TITLE
Test Walkthrough #1 Doesn't Work

### ISSUE THREAD

**Issue by tmack8080** [adbertram/pesterbookcode#1]
After copying the 'Execution' block code from the text, the test script fails:

 [-] when the Web-Mgmt-Service feature is already installed, it changes the EnableRemoteManagement reg value to 1 66ms
        CommandNotFoundException: The term 'true' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I also tried manually typing in the code; same error.
[Enable-IISRemoteManagement.Tests.zip](https://github.com/adbertram/pesterbookcode/files/3444195/Enable-IISRemoteManagement.Tests.zip)

**Comment by tmack8080** [comment]
Typo in the script file. Error was calling out the test file. Working now.

**Comment by adbertram** [comment]
Can you tell me where this is in the book so I can fix it?

**Comment by tmack8080** [comment]
It was my typo. I plan to submit all the typos I've found once I complete
the book.Likely a few weeks from now.

Feel free to take down my post as not to confuse others.
